[package]
name = "Ribbit"
version = "0.1.0"
authors = ["Helba <helba@netslum.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mailparse = "0.13.2"
